//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCM.WebApp.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int Id { get; set; }
        public Nullable<int> ServiceInformationId { get; set; }
        public Nullable<int> InfoTypeId { get; set; }
        public string InformationContent { get; set; }
        public string FileExt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
    
        public virtual InfoType InfoType { get; set; }
        public virtual ServiceInformation ServiceInformation { get; set; }
    }
}
